name: Deploy Frontend to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Docker image
        run: |
          docker build -t wow-frontend-image -f Dockerfile.prod .
          docker save wow-frontend-image > wow-frontend-image.tar
      
      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@master
        with:
          source: wow-frontend-image.tar
          target: ec2-user@${{ secrets.EC2_HOST }}:~/wow-frontend-image.tar
          key: ${{ secrets.EC2_SSH_KEY }}
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker load < ~/wow-frontend-image.tar
            docker stop wow-frontend || true
            docker rm wow-frontend || true
            docker run -d \
              --name wow-frontend \
              -p 80:80 \
              --restart unless-stopped \
              wow-frontend-image
            rm ~/wow-frontend-image.tar
            docker system prune -af
