name: Deploy to EC2

on:
  push:
    branches: [ main ]  # or whatever your main branch is named

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'  # In case you have submodules
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to project directory
            cd ~/wow-character-viewer
            
            # Pull latest changes
            git pull origin main
            
            # Stop running containers
            docker-compose down
            
            # Remove old images to ensure clean build
            docker system prune -f
            
            # Rebuild and start containers in detached mode
            docker-compose up --build -d
            
            # Print container status
            docker ps
